### ISSUE TITLE
Welcome new contributor - GitHub Action

### ISSUE THREAD

**Issue by JSerwatka** [SikoraWojciech/Nuxt-Headless-CMS#1]
I can add a GitHub Action that will post a welcome message whenever a new contributor opens his/her first issue or PR in your repository.

It looks something like this:
![image](https://raw.githubusercontent.com/garg3133/welcome-new-contributors/main/assets/github-actions-bot.png)

But you can also customize it to use your profile to make a comment. Like this:
![image](https://user-images.githubusercontent.com/33938646/115193856-fc446980-a0ec-11eb-9aeb-c13a9d9574fc.png)

I have a yml file for this already written, so we can discuss what the messages should look like.

**Comment by WojtekTheWebDev** [comment]
Hi @JSerwatka, I'd be very happy if you can add it :)
