### ISSUE TITLE
Website link in the project's description

### ISSUE THREAD

**Issue by JSerwatka** [SikoraWojciech/Nuxt-Headless-CMS#2]
You could add a link to your [Live Demo](https://nuxt-headless-cms.herokuapp.com/) in the project's description.

You can do it here:
![image](https://user-images.githubusercontent.com/33938646/115194338-a02e1500-a0ed-11eb-83b4-91f5a2637fde.png)

**Comment by WojtekTheWebDev** [comment]
Added, thanks!
